[[clips]]
title = "Cat and dog are best friends"
url = "https://www.youtube.com/shorts/r1X0lVMP7us"

[[clips]]
title = "This cat and dog are best friends"
url = "https://www.youtube.com/shorts/5cUoJTvycL0"

[[clips]]
title = "Cat comforts a blind dog"
url = "https://www.youtube.com/shorts/mpbuHFT7PfU"

[[clips]]
title = "Dog and kitten become best friends"
url = "https://www.youtube.com/shorts/7nUbsCDOFhI"
